:-op(1100,xfx,:::).
:-op(700,xfx,⊢).
:-op(600,xfy,[$,<:,#]).
_⊢T<:T:-!.
Γ⊢T1<:T2:-member(Elm,Γ),Elm==(T1<:T2),!.
_⊢T1<:T2:-var(T1),var(T2),!,T1=T2.
Γ⊢T1<:T2:-var(T1),!,(is_list(T2)->member(Y,T2),(T1=Y;[T1<:T2|Γ]⊢T1<:Y);T1=T2).
Γ⊢T2<:T1:-var(T1),!,(is_list(T2)->member(Y,T2),(T1=Y;[T1<:T2|Γ]⊢T1<:Y);T1=T2).
Γ⊢T1<:T2:-(T1:::R1),R1\=(_->_),!,[T1<:T2|Γ]⊢R1<:T2.
Γ⊢T1<:T2:-(T2:::R2),R2\=(_->_),!,[T1<:T2|Γ]⊢T1<:R2.
Γ⊢r(P1)<:r(P2):-!,forall(member(L:X2,P2),(member(L:X1,P1),[r(P1)<:r(P2)|Γ]⊢X1<:X2)).
Γ⊢T1<:T2:-is_list(T1),is_list(T2),!,forall(member(X,T1),([T1<:T2|Γ]⊢[X]<:T2)).
Γ⊢[r(P1)]<:[r(P2)]:-!,[[r(P1)]<:[r(P2)]|Γ]⊢r(P1)<:r(P2).
Γ⊢[X]<:T2:-is_list(T2),!,member(Y,T2),(X=Y;[X<:T2|Γ]⊢X<:Y),!.
Γ⊢X<:T2:-is_list(T2),!,member(Y,T2),(X=Y;[X<:T2|Γ]⊢X<:Y),!.
Γ⊢(T11->T12)<:(T21->T22):-!,
  [(T11->T12)<:(T21->T22)|Γ]⊢T12<:T22,
  maplist(check_sub(Γ),T21,T11).
check_sub(Γ,X,Y):-Γ⊢X<:Y.
tp(Γ,M,T):-var(M),!,lookup_env(M,T,Γ).
tp(_,M,T):-integer(M),!,[]⊢int_t<:T.
tp(_,M,T):-atom(M),(M:::[]->T1),!,[]⊢T1<:T.
tp(_,M,T):-atom(M),!,[]⊢atom_t<:T.
tp(_,[],T):-!,([]⊢list(_A)<:T;[]⊢T<:list(_A)).
tp(Γ,[H|Tail],T):-!,([]⊢list(A)<:T;[]⊢T<:list(A)),tp(Γ,H,A),tp(Γ,Tail,list(A)).
tp(Γ,M,T):-compound(M),!,M=..[C|Ms],(C:::Ts->T1),[]⊢T1<:T,maplist(tp(Γ),Ms,Ts).
lookup_env(M,T,[M1:T1|_]):-M==M1,!,([]⊢T<:T1;[]⊢T1<:T).
lookup_env(M,T,[Elm|_]):-var(Elm),!,Elm=(M:T).
lookup_env(M,T,[_|Rest]):-lookup_env(M,T,Rest).
goal(Γ,G):-G=..[P|Ms],(P:::Ts),maplist(tp(Γ),Ms,Ts).
body(_,true):-!.
body(Γ,(A,B)):-!,body(Γ,A),body(Γ,B).
body(Γ,G):-goal(Γ,G).
check(Γ,Head:-Body):-goal(Γ,Head),body(Γ,Body).
check(Γ,Head):-goal(Γ,Head).
'[|]':::[A,list(A)]->list(A).
append:::[list(X),list(X),list(X)].
expr:::[int_t,int,(+),(*),($),λ,atom_t].
int:::[int_t]->expr.
eval:::[expr,int_t].
integer:::[int_t].
is:::[int_t,int_t].
(+):::[expr,expr]->int_t.
(*):::[expr,expr]->int_t.
v:::[int_t,[v]->v].
env:::list(atom_t:v).
clause:::[env,atom_t,expr]->([v]->v).
ev:::[env,expr,v].
ev:::[expr,v].
var:::[atom_t]->expr.
λ:::[atom_t,expr]->expr.
($):::[expr,expr]->expr.
(:):::[atom_t,V]->atom_t:V.
member:::[A,list(A)].
atom:::[atom_t].
(!):::[].

(->):::[t,t]->t.
i:::[]->t.
t:::[i,->].
tc:::[expr,t].

:-begin_tests(t).
test(1):-check(_,(append([1],[2],[1,2]):-true)),!.
test(2):-check(_,(eval(int(I),I):-integer(I))),!.
test(3):-check(_,(eval(E1+E2,I):-eval(E1,I1),eval(E2,I2),I is I1+I2)),!.
test(4):-check(_,(eval(E1*E2,I):-eval(E1,I1),eval(E2,I2),I is I1*I2)),!.
test(5):-check(_,(ev(I,I):-integer(I))),!.
test(6):-check(_,(ev(_,I,I):-integer(I),!)),!.
test(7):-check(_,(ev(Γ,E1+E2,I):-ev(Γ,E1,I1),ev(Γ,E2,I2),I is I1+I2)),!.
test(8):-check(_,(ev(Γ,E1*E2,I):-ev(Γ,E1,I1),ev(Γ,E2,I2),I is I1*I2)),!.
test(9):-check(_,(ev(Γ,X,V):-atom(X),!,member(X:V,Γ))),!.
test(10):-check(_,(ev(Γ,E1$E2,I):-ev(Γ,E1,clause(Γ2,X,E)),ev(Γ,E2,V2),ev([X:V2|Γ2],E,I))),!.
test(11):-check(_,(ev(Γ,λ(X,E),clause(Γ,X,E)))),!.
test(12):-[]⊢int<:expr,!.
test(13):-[]⊢i<:t,!.
test(14):-check(_,(tc(I,i):-integer(I))),!.

:-end_tests(t).
:-run_tests.
:-halt.
